version: '3.8'

services:
 mariaDB:
  container_name: mariadb
  build:
	 context: ./requirements/mariadb/
   dockerfile: Dockerfile
	env_file:
	 - ./.env
	volumes:
	 - mariadb_data:/var/lib/mysql
	networks:


 wordpress:
  container_name: wordpress
	build:
	 context: ./requirements/wordpress/
	 dockfile: Dockerfile
	depends_on:
		- mariadb
	env_file:
	 - ./.env
	volumes:
	 - wordpress_data:/var/www/wordpress
	networks:


 nginx:
  container_name: nginx
	build:
		context: ./requirements/nginx/
		dockerfile: Dockerfile
	env_file:
	 - ./.env
	depends_on:
		-wordpress
	volumes:
	networks:
	
	

	

networks:

volumes:
 mariadb:
  name: mariadb_data
   driver_opts:
    type: none
    device: /home/osabir/data/mariadb
    o: bind
 wordpress:
  name: wordpress_data
	 driver_opts:
	  type: none
		device: /home/osabir/data/wordpress
		o: bind
	  

			 
