version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:incption
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - incption_mariadb_data:/var/lib/mysql
    networks:
      - incption_net

  wordpress:
    container_name: wordpress
    image: wordpress:incption
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    env_file:
      - ./.env
    volumes:
      - incption_wordpress_data:/var/www/wordpress
    networks:
      - incption_net

  nginx:
    container_name: nginx
    image: nginx:incption
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "$NGINX_PORT:$NGINX_PORT"
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - wordpress
    volumes:
      - incption_wordpress_data:/var/www/wordpress
    networks:
      - incption_net
    

networks:
  incption_net:
    name: incption_net  

volumes:
  incption_mariadb_data:
    driver_opts:
      type: none
      device: $DB_DATA
      o: bind
  incption_wordpress_data:
    driver_opts:
      type: none
      device: $WP_DATA
      o: bind
