FROM debian:bullseye

# Update and upgrade system packages
RUN apt-get update && apt-get upgrade -y

RUN apt-get install mariadb-server -y

COPY ./tools/script.sh /tmp/

RUN chmod +x /tmp/script.sh

EXPOSE 3306

CMD ["/tmp/script.sh"]
