FROM debian:bullseye

# Update and upgrade system packages
RUN apt-get update && apt-get upgrade -y

RUN apt-get install mariadb-server -y

COPY ./tools/scrpt.bash /tmp/

RUN chmod +x /tmp/scrpt.bash

EXPOSE 3306

CMD ["bash", "./tmp/scrpt.bash"]

