FROM debian:buster


RUN apt update -y 
RUN apt upgrade -y
RUN apt install mariadb-server -y


COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY tools/script.sh /tmp/script.sh
RUN chmod +x /tmp/script.sh
RUN bash /tmp/script.sh

# CMD ["bash", "/tmp/script.bash"]